#! /usr/bin/env python

"""
Command-line tool to interogate an instance of a Gerrit Code Review server.
"""

import os
import sys

from libpycr.commandline import parse_command_line
from libpycr.config import Config
from libpycr.exceptions import PyCRError
from libpycr.utils.system import format_message


def cl_main(arguments):
    """
    The main function of this module.

    Takes care of parsing the command line and process the user request.

    PARAMETERS
        arguments: the argument array as provided on the command-line
    """

    try:
        # Load various input configurations
        Config.load_all()

        # Fetch the result of the command-line parsing
        command, command_arguments = parse_command_line(arguments)

        # Execute the requested command
        command(command_arguments)

    except PyCRError as why:
        sys.exit(format_message(str(why), prefix='fatal'))

    except KeyboardInterrupt:
        sys.exit('%sInterruption caught...' % os.linesep)

    sys.exit()


# Script entry point
# If executed (and not imported), parse the command line and process the
# request.

if __name__ == '__main__':
    cl_main(sys.argv)
