#! /usr/bin/env python

"""Integrate Gerrit with Git"""

# pylint: disable=C0103
# Disable "Invalid module name" (this is not a module but a script)

from libpycr.main import builtin_main
from libpycr.meta import GitClBuiltin

# git-cl entry point

if __name__ == '__main__':
    builtin_main(GitClBuiltin)
