#! /usr/bin/env python

"""Integrate Gerrit with Git"""

# pylint: disable=invalid-name, wildcard-import
from libpycr.builtin.changes import *  # NOQA

from libpycr.main import builtin_main
from libpycr.meta import GitClBuiltin

# git-cl entry point

if __name__ == '__main__':
    builtin_main(GitClBuiltin)
